#define COLOR_YELLOW 			0xFFFF00FF
#define COLOR_SERVER      		0xC6E2FFFF
#define COLOR_GREY   			0xAFAFAFFF
#define COLOR_PURPLE 			0xD0AEEBFF
#define COLOR_CLIENT 			0xC6E2FFFF
#define COLOR_WHITE  			0xFFFFFFFF
#define COLOR_LIGHTRED    		0xFF6347FF
#define COLOR_LIGHTGREEN  		0x9ACD32FF
#define COLOR_RADIO 			0x8D8DFFFF
#define COLOR_DEPARTMENT		0xF0CC00FF
#define COLOR_GREEN       		0x33CC33FF
#define COLOR_OLDGREEN          0x2D5A28FF
#define COLOR_RED 				0xFF0000FF
#define COLOR_LIGHTORANGE   	0xF7A763FF

#define SERVER_E    "{C6E2FF}"
#define CYAN_E      "{00FFFF}"
#define AQUA        "{7FFFD4}"
#define FAMILY_E    "{F77AFF}"
#define PURPLE_E2   "{7348EB}"
#define RED_E       "{FF0000}"
#define BLUE_E      "{004BFF}"
#define SBLUE_E     "{56A4E4}"
#define PINK_E      "{FFB6C1}"
#define YELLOW_E    "{FFFF00}"
#define LG_E        "{00FF00}"
#define LB_E        "{15D4ED}"
#define LB2_E       "{87CEFA}"
#define GREY_E      "{BABABA}"
#define GREY2_E     "{778899}"
#define GREY3_E     "{C8C8C8}"
#define DARK_E      "{7A7A7A}"
#define WHITE_E     "{FFFFFF}"
#define WHITE       "{FFFFFF}"
#define WHITEP_E    "{FFE4C4}"
#define IVORY_E     "{FFFF82}"
#define ORANGE_E    "{DB881A}"
#define ORANGE_E2   "{FF5000}"
#define GREEN_E     "{00FF00}"
#define OLDGREEN_E  "{2D5A28}"
#define PURPLE_E    "{5A00FF}"
#define ANS_E       "{FF9945}"
#define LIME_E      "{D2D2AB}"
#define LRED_E      "{E65555}"
#define SILVER_E    "{999999}"
#define DOOM_       "{F4A460}"
#define MATHS       "{3571FC}"
#define REACTIONS   "{FD4141}"
#define LBLUE       "{FFAA00}"
#define RIKO        "{ADD8E6}"
#define ERROR_E     "{AFAFAF}"